services:
  - type: web
    name: cctv-ai-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        fromService:
          type: web
          name: cctv-ai-server
          property: port